# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c67e0b0fa48dcb8dafc4b32128b4dbed29408fcfe1eb780ce6a1eae284e44717801279a7a5504006e3a00b77664b16b23a4ef3b8be6f1cd1bcafaa3c2db4b55

test:
  secret_key_base: 150d9e30e9038f9939d0382e5330df2f8ef6630850e9c542c8f17484ae113fcf323236c5be86f25dbb660d1893e7b6bf27cb8a19dcbcfae002ba3ee15c6f94a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
